### ISSUE TITLE
Add a way to craft/buy (with gold) unobtainable items such as primarine

### ISSUE THREAD

**Issue by dextonanderson** [Ruinscraft/mcatlas-issues#5]

**Comment by dextonanderson** [comment]
Saddles

**Comment by drewdorris** [comment]
Totem of undying, beetroot seeds, lava buckets/obsidian(could be major shortage)

**Comment by dextonanderson** [comment]
Slime balls?

**Comment by drewdorris** [comment]
Several of these have been added to mcmmo fishing, possibly all of them could be?

**Comment by drewdorris** [comment]
Heart of the sea

**Comment by drewdorris** [comment]
Phantom membrane

**Comment by bomba1749** [comment]
please either remove the overfishing thing or make there a way to get these items without fishing, both of these create an artificial demand, make people less likely to stay around as fishing requires so much time, and makes the server way more grindy, which imo isnt how the server should operate (if you want to grind something, go on runescape) Along with that, since afk fishers wont work with mcmmo unless you accept the high risk of your loop breaking and your fishing rod dissapearing forever, there isnt really any potential for abuse.

**Comment by dextonanderson** [comment]
> 
> 
> please either remove the overfishing thing or make there a way to get these items without fishing, both of these create an artificial demand, make people less likely to stay around as fishing requires so much time, and makes the server way more grindy, which imo isnt how the server should operate (if you want to grind something, go on runescape) Along with that, since afk fishers wont work with mcmmo unless you accept the high risk of your loop breaking and your fishing rod dissapearing forever, there isnt really any potential for abuse.

I agree. I don't think we should necessarily remove them from mcmmo fishing but there should be additional crafting recipes for these items.

**Comment by dextonanderson** [comment]
https://github.com/EarthMC/EMCRecipies/blob/master/src/main/java/com/karlofduty/EMCRecipies/EMCRecipies.java Its GPL... Could use just as an example

**Comment by bomba1749** [comment]
maybe give the unemployed villager trades for some of these?

**Comment by drewdorris** [comment]
Implemented all of these, possibly reopen if we think of more
